# tag: docker build -t cheesecake87/pdf-generator-service-gfonts:b2-arm -t cheesecake87/pdf-generator-service-gfonts:latest .
# tag: docker build --platform linux/amd64 -t cheesecake87/pdf-generator-service-gfonts:b2-x86 -t cheesecake87/pdf-generator-service-gfonts:latest .
FROM ghcr.io/astral-sh/uv:python3.14-alpine

RUN apk add --update --upgrade --no-cache fontconfig ttf-freefont font-noto terminus-font && fc-cache -f && fc-list | sort
RUN apk add --update --no-cache py3-pip gcc musl-dev python3-dev pango zlib-dev jpeg-dev openjpeg-dev g++ libffi-dev curl curl-dev
RUN apk add --update --no-cache linux-headers tzdata
RUN apk add so:libgobject-2.0.so.0  \
    so:libpango-1.0.so.0 so:libharfbuzz.so.0  \
    so:libharfbuzz-subset.so.0 so:libfontconfig.so.1  \
    so:libpangoft2-1.0.so.0

ENV TZ=Europe/London

RUN mkdir /fonts
COPY fonts /fonts

WORKDIR /main

COPY app app
COPY env env
COPY pyproject.toml pyproject.toml
COPY uv.lock uv.lock

# Install the project's dependencies using the lockfile and settings
RUN uv sync --no-dev
# Place executables in the environment at the front of the path
ENV PATH="/main/.venv/bin:$PATH"

ENTRYPOINT ["qwe", "granian"]
