[project]
name = "PDF-Generator-Service"
version = "1.2.0"
description = "An API service for generating PDFs from given html"
requires-python = ">=3.14"
dependencies = [
    "flask==3.1.3",
    "weasyprint>=68.1",
    "pyqwe>=3.1.2",
    "marshmallow>=4.3.0",
    "flask-orjson>=2.0.0",
    "granian>=2.7.4",
    "python-dotenv>=1.2.2",
]

[tool.pyqwe]
dev = "*:flask run --port 9898 --debug"
granian = [
    "@sync",
    "env:load",
    "*:granian app:main"
]

[dependency-groups]
dev = [
    "requests>=2.33.1",
    "ruff>=0.15.12",
]
